language: node_js
sudo: false
node_js:
- 'lts/*'

addons:
  chrome: stable

cache:
  yarn: true

env:
  - CANARY=false
  - CANARY=true

matrix:
  fast_finish: true
  allow_failures:
    - env: CANARY=true

branches:
  only:
    - master # otherwise pull requests get built twice

before_install:
  - cd reactfire

install:
  - |
    if $CANARY; then
      yarn upgrade && yarn add firebase@canary && yarn add rxfire@canary
    else
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        yarn upgrade
      else
        yarn install --frozen-lockfile
      fi
    fi

script:
  - yarn build
  - yarn test