# See go/reactfire-releasing for details on the ReactFire release process.
# If you need to trigger a release manually, be sure to use substitutions like so:
#   @canary `gcloud builds submit --substitutions=SHORT_SHA="9b0a0b0"`
#   @next   `gcloud builds submit --substitutions=TAG_NAME="v1.2.3-rc.1"`
#   @latest `gcloud builds submit --substitutions=TAG_NAME="v1.2.3"`
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/reactfire/docker']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/reactfire/docker', '--cache-from', 'gcr.io/reactfire/docker']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/reactfire/firebase']
- name: 'gcr.io/reactfire/docker'
  args: ['install', '--frozen-lockfile']
- name: 'gcr.io/reactfire/docker'
  dir: 'reactfire'
  args: ['build']
- name: 'gcr.io/reactfire/docker'
  dir: 'reactfire'
  args: ['test']
- name: 'gcr.io/reactfire/docker'
  dir: 'reactfire/pub/reactfire'
  entrypoint: 'bash'
  env:
  - 'SHORT_SHA=$SHORT_SHA'
  - 'TAG_NAME=$TAG_NAME'
  args: ["../../../publish.sh"]
  secretEnv: ['NPM_TOKEN']

secrets:
- kmsKeyName: projects/reactfire/locations/global/keyRings/cloud-build/cryptoKeys/cloud-build
  secretEnv:
    NPM_TOKEN: CiQADamFn5XzbeNQgzTGST9r3Tp5skWlDbBiWaZljffgEm0yIxYSTQC1QbtmDtScXx1BPE+d3CP9rXvOY+n5J0XRuLTTqN7RaqyipCEqTi7+z1kI6mKyBo2ilsMtOtngNzbOZ8kZeUDA80ISLWrNs0hF8k78

images:
- gcr.io/reactfire/docker